# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in _Layout.cshtml with BuildId'
  inputs:
    rootDirectory: app/Pages/Shared/
    targetFiles: '_Layout.cshtml'
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.0.100-preview5-011568'
  inputs:
    version: '3.0.100-preview5-011568'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: app/app.csproj
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: test/test.csproj
- task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'
