# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#trigger:
#- master

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - sampleapp/*
    - test/*
    exclude:
    - exclude-from-build/*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in _Layout.cshtml with BuildNumber'
  inputs:
    rootDirectory: sampleapp/Pages/Shared/
    targetFiles: '_Layout.cshtml'
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.0.100-preview5-011568'
  inputs:
    version: '3.0.100-preview5-011568'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: sampleapp/sampleapp.csproj
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: test/test.csproj
