# create sample namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
# create service account that pods will run using
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
  namespace: sample
automountServiceAccountToken: false
---
# create role that PODs will be assigned
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: sample-role
 namespace: sample
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
# Bind role to sample service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: sample-rolebinding
 namespace: sample
roleRef:
 kind: Role
 name: sample-role
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sample
  namespace: sample
---
# Deploy 2 instances of image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: sample
  labels:
    app: sample
  annotations:
    created: N Wardle
    organisation: CDW
    for: Clyde & Co
    buildversion: #{Build.BuildNumber}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: sample
      securityContext:
        runAsUser: 0  #admin
      containers:
      - name: sample
        image: ccukssbacr.azurecr.io/sample:#{Build.BuildNumber}#
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        env:
        - name: version
          value: "1.0"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: 
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "750Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
---
# expose pods to service on private IP
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: sample
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" # set to true for private IP

    # important: the AKS Service Principle must have Network Contributor permissions to the RG that hosts the ILB VNET .e.g see below
    # https://docs.microsoft.com/en-us/azure/aks/internal-lb
    # az role assignment create --assignee caa68f4b-b41e-4d36-9000-c2a3f3606a19 --role "Network Contributor" --resource-group cc-uks-rsg-leap-sb-network
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cc-uks-leap-sb-snet-ilb-01" # specify subnet
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample

