---
# expose pods to service on public IP
apiVersion: v1
kind: Service
metadata:
  name: sample-public
  namespace: sample
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" # set to true for private IP
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cc-uks-leap-sb-snet-plb-01" # specify subnet
spec:
  type: LoadBalancer
  loadBalancerIP: 10.125.6.40
  ports:
  - port: 80
  selector:
    app: sample