apiVersion: v1
kind: Service
metadata:
  name: sample-public
  namespace: sample
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" # set to true for private IP
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample