---
# expose pods to service on private IP
apiVersion: v1
kind: Service
metadata:
  name: sample-public
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" # set to true for public IP
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet" # specify subnet
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample