apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
 name: sample-rolebinding
 namespace: sample
roleRef:
 kind: Role
 name: sample-role
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sample
  namespace: sample
