apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      serviceAccountName: sample
      containers:
      - name: sample
        image: nginx
        env:
        - name: version
          value: "1.0"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: 
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "750Mi"
            cpu: "750m"
        ports:
        - containerPort: 80