apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: sample-role
 namespace: sample
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]